Adds server-provided nonces for Client Attestation PoP JWT freshness verification
oauth-wg/draft-ietf-oauth-attestation-based-client-auth pull request #64
Opened 2023-11-14 14:08 UTC by pmhsfelix

Closes #59

## 📑 Description
This PR adds server-provided nonces as a way to check the freshness of Client Attestation PoP JWT, in a similar way to what is done in DPoP (RFC 9449).

## Preview Link

NA

2023-11-15 07:49 UTC, peppelinux commented on draft-ietf-oauth-attestation-based-client-auth.md
> +The client MUST use this new nonce value to create a new Client Attestation PoP JWT and resend the previous request.
```suggestion
The Client MUST use this new nonce value to create a new Client Attestation PoP JWT and resend the previous request.
```
@pmhsfelix I'm wondering if using Client as defined term in OAuth 2.0. If yes this change is required within the entire text

2023-11-15 08:36 UTC, tlodderstedt approved these changes
lgtm

2023-11-15 10:10 UTC, ju-cu approved these changes
I suggest some normative language for the `nonce` syntax and HTTP error message. All in all good, so green light from me.

2023-11-15 15:53 UTC, paulbastian commented
This is the obvious solution going in the right direction. I'm not convinced yet that this is the ideal solution, especially in combination with DPoP.

2023-11-16 08:02 UTC, peppelinux requested changes
just editorial, consider it approved

2023-11-16 08:02 UTC, peppelinux commented on draft-ietf-oauth-attestation-based-client-auth.md
> +This requirement is communicated to the client by having the authorization server return an HTTP response with the `400` status and an `error` field with the value `"use_attestation_nonce"`, when the
```suggestion
This requirement is communicated to the Client by having the authorization server return an HTTP response with the `400` status and an `error` field with the value `"use_attestation_nonce"`, when the Client Attestation PoP JWT present in the HTTP request does not contain a valid nonce.
```

2023-11-16 18:40 UTC, bc-pi commented
> That ties two mechanisms together that were built for different purposes. 

The [DPoP proof JWT ](https://www.rfc-editor.org/rfc/rfc9449.html#name-dpop-proof-jwts) part of RFC9449 was built exactly for the purpose of proving possession of a key in the context of an HTTP request. And can be used without necessarily binding access tokens.

2023-11-16 19:04 UTC, pmhsfelix commented
>@bc-pi
>There's a lot of overlap and duplicative text and functionality with DPoP in this nonce mechanism and the Client Attestation PoP JWT itself. A lot. It makes me question (again) if it wouldn't be better to use the DPoP Proof JWT as the PoP mechanism in this work rather than recreate so much of it with the Client Attestation PoP JWT.

Also had the exact same feeling while writing the PR, namely the creation of a duplicate header and a duplicate OAuth error code. Using DPoP for the proof-of-possession did also cross my mind.

We could perhaps decouple the DPoP proof of possession JWT from the `DPoP` HTTP header. 
My current understanding is that the `DPoP` header serves *two* purposes when used on a Token Request:
- Convey a public key proof-of-possesion JWT.
- Request the issued tokens to be bound to that public key.
OTOH, when used on a Resource Server request, the `DPoP` header seems to only serve the first purpose.

If we want to use DPoP all the way, then this seems to work perfectly. 
However, if we don't want to bind the access tokens using DPoP, we could still use the DPoP proof of possession JWT but convey it in a different way (e.g. on the token request body or on a different header, instead of on the `DPoP` header). The `DPoP-nonce` and `use_dpop_nonce` could still be used to provide a fresher nonce.

2023-11-16 21:44 UTC, bc-pi commented
DPoP itself specifically has text in the [DPoP Access Token Request](https://www.rfc-editor.org/rfc/rfc9449.html#name-dpop-access-token-request) section that [allows for an AS to issue access tokens that are not DPoP bound](https://www.rfc-editor.org/rfc/rfc9449.html#section-5-9). 

> An authorization server MAY elect to issue access tokens that are not DPoP bound, which is signaled to the client with a value of Bearer in the token_type parameter of the access token response per [RFC6750].

And this draft could certainly reiterate that, if it went with the DPoP proof as its PoP mechanism.

There is and has been (it's come up previously) a lot of resistance to that approach though. But maybe that resistance was from the misconception that DPoP usage at the token endpoint meant that access tokens had to be DPoP bound.

2023-11-17 02:51 UTC, tplooker commented
> > [...] if we don't want to bind the access tokens using DPoP, [...]
> 
> DPoP itself specifically has text in the [DPoP Access Token Request](https://www.rfc-editor.org/rfc/rfc9449.html#name-dpop-access-token-request) section that [allows for an AS to issue access tokens that are not DPoP bound](https://www.rfc-editor.org/rfc/rfc9449.html#section-5-9). It says:
> 
> > An authorization server MAY elect to issue access tokens that are not DPoP bound, which is signaled to the client with a value of Bearer in the token_type parameter of the access token response per [RFC6750].
> 
> And this draft could certainly reiterate that, if it went with the DPoP proof as its PoP mechanism.
> 
> There is and has been (it's come up previously) a lot of resistance to that approach though. But maybe that resistance was from the misconception that DPoP usage at the token endpoint meant that access tokens had to be DPoP bound.

At least I'd failed to realise this language existed in DPoP and it feels like because of that I dont really see why we shouldn't consider using the DPoP format for the PoP, it feels both generalised enough for other endpoints AND doesn't mandate the tokens issued from the token endpoint are DPoP bound.

2023-11-17 16:46 UTC, pmhsfelix commented
So we would use the DPoP token format *and* convey it via the `DPoP` header? Or just use the DPoP token format (and associated nonce management)?

2023-11-17 18:39 UTC, paulbastian commented
I'm somehow hesitant to put everything in the headers.

I think we should evaluate to reuse the key from the client attestation as a key for dpop binding and somehow reuse the nonce providing mechanism. As this is a major use case in mind, we should avoid sending multiple nonces, using multiple keys and proofs.

2023-11-24 08:21 UTC, ju-cu commented
I also prefer to reuse existing specs, i.e. DPoP (RFC 9449) and Assertion based client authentication (RFC 7521), over copying text. This spec already profiles RFC 7521 but could also use DPoP to satisfy the key-binding of the client attestation. Instead of concatenating two JWTs into a single assertion, the `client_assertion` parameter should hold a key-binding JWT, aka the client attestation JWT. The DPoP HTTP header holds the DPoP proof JWT that serves as the client attestation PoP JWT. In that way, there is no need to define the client attestation PoP JWT in this spec as it can just point to DPoP and use all the mechanisms defined there, including the nonce mechanism. A token request would look like this:

```http
POST /token HTTP/1.1
Host: as.example
Content-Type: application/x-www-form-urlencoded
DPoP: eyJ0eXAiOiJkcG9wK2p3dCIsImp3ayI6eyJhbGciOiJFUzI1NiIsImNydiI6IlAtMjU2Iiwia3R5IjoiRUMiLCJ4IjoiaThReW03NFRNUHVLQXVKUGlZczFSZlVsYTVjemNxelVobEpmRHNMdzd0NCIsInkiOiJGQjlUY2ZmeVZDSEpFQjJjejc4NTE2MUE0SmxlTkh2cG44bXhHRldZMlNjIn0sImFsZyI6IkVTMjU2In0.eyJqdGkiOiIzNTc2ODI5Ny1kZWM1LTQ2ZjYtODVlNS1iNzU4MjE2YWI1ZmYiLCJodG0iOiJQT1NUIiwiaHR1IjoiaHR0cHM6Ly9hcy5leGFtcGxlL3Rva2VuIiwiaWF0IjoxNzAwODEyODAwLCJub25jZSI6ImV5SjdTX3pHLmV5SkgwLVouSFg0dy03diJ9.5VuDrkd8RhMRaps_AzJBs2p-_UXXWT4dVHITBHiQxe31GeDq81otnIh3HBQN8_XjS1diHPq1tti1pn55eZdI5g

grant_type=authorization_code&
code=n0esc3NRze7LTCu7iYzS6a5acc3f0ogp4&
client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-client-attestation&
client_assertion=eyJhbGciOiJSUzI1NiIsImtpZCI6IjIyIn0.eyJpc3Mi[...omitted for brevity...].cC4hiUPo[...omitted for brevity...]

```

where the DPoP proof JWT decodes as follows:
```json
JOSE Header
{
  "typ": "dpop+jwt",
  "jwk" : {
    "alg": "ES256",
    "crv": "P-256",
    "kty": "EC",
    "x": "i8Qym74TMPuKAuJPiYs1RfUla5czcqzUhlJfDsLw7t4",
    "y": "FB9TcffyVCHJEB2cz785161A4JleNHvpn8mxGFWY2Sc"
   }
  "alg": "ES256"
}

Payload
{
  "jti": "35768297-dec5-46f6-85e5-b758216ab5ff",
  "htm": "POST",
  "htu": "https://as.example/token",
  "iat": "1700812800",
  "nonce": "eyJ7S_zG.eyJH0-Z.HX4w-7v"
}
```

Note, that the DPoP proof JWT MUST contain the `jwk` parameter in the JOSE header according to RFC 9449. In the context of client authentication as defined in this spec, the authorization server MUST use the public key from the `cnf` claim of the `client_attestation` to validate the DPoP proof. The authorization server MAY ignore the `jwk` parameter of the DPoP proof JWT.

2023-11-29 21:19 UTC, bc-pi commented
@ju-cu's description of how the DPoP proof JWT would serve as the client attestation PoP JWT is pretty much in line with how I'd envisioned it. Although I believe it'd need to be a bit less prescriptive about checking the confirmation/pop key and just say that the public key from the `cnf` of Client Attestation JWT must match the key of the `jwk` header of the DPoP proof JWT. This would allow for the _conventional_ processing order with DPoP where the DPoP proof JWT is validated first followed by binding to or checking the binding of things against the key of the DPoP proof JWT.

2024-01-15 21:29 UTC, tplooker commented
Please see #67 for a concrete proposal to shift to using DPoP as the PoP syntax for this client authentication method.

2024-02-04 00:46 UTC, peppelinux commented
After giving it much thought, I realized that DPoP uses HTTP headers in HTTP requests, and consequently, it makes sense to obtain a nonce within the headers of the received HTTP responses.

Meanwhile, the nonces we use in OAuth and for endpoint requests utilize GET or POST parameters, and the idea of forcibly using HTTP headers for nonce provisioning doesn't excite me.

We already have a nonce endpoint in IETF literature, for example in ACME (RFC8555), and with the aim of creating something highly specialized, reusable in other contexts, efficient, and scalable, I thought of this:

https://github.com/peppelinux/draft-demarco-nonce-endpoint

2024-08-22 09:02 UTC, paulbastian commented
We had a discussion on this topic in today's editors call, I posted my thoughts here: https://github.com/oauth-wg/draft-ietf-oauth-attestation-based-client-auth/issues/59#issuecomment-2304146071

2025-03-03 19:08 UTC, tplooker commented
Closing given we have merged in #99

2025-03-03 19:08 UTC, closed without merging